rate: 25
source_list:
  ['/hh/joint_states', '/WsgData/JointState']
dependent_joints:
  gripper_finger1_joint: {parent: gripper_joint, factor: -0.5}
  gripper_finger2_joint: {parent: gripper_joint, factor: 0.5}
