controller_list:
  - name: bh/EffortJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - bh_joint_1
      - bh_joint_2
      - bh_joint_3
      - bh_joint_4
      - bh_joint_5
      - bh_joint_6
      - bh_joint_7
