controller_list:
  - name: hh/EffortJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - hh_joint_1
      - hh_joint_2
      - hh_joint_3
      - hh_joint_4
      - hh_joint_5
      - hh_joint_6
      - hh_joint_7

